export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/Zentar-Ai/roo-code",
	GITHUB_DISCUSSIONS: "https://github.com/Zentar-Ai/Roo-Code/discussions",
	DISCORD: "https://discord.gg/your-discord-invite",
	REDDIT: "https://www.reddit.com/r/your-subreddit",
	X: "https://x.com/your-profile",
	LINKEDIN: "https://www.linkedin.com/company/your-company",
	TIKTOK: "https://www.tiktok.com/@your-profile",
	BLUESKY: "https://bsky.app/profile/your-profile.bsky.social",
	YOUTUBE: "https://www.youtube.com/@RooCodeYT",
	DOCUMENTATION: "https://docs.zentar.ai",
	CAREERS: "https://careers.zentar.ai",
	ISSUES: "https://github.com/Zentar-Ai/Roo-Code/issues",
	FEATURE_REQUESTS: "https://github.com/Zentar-Ai/Roo-Code/discussions/categories/feature-requests",
	COMMUNITY: "https://github.com/Zentar-Ai/Roo-Code/discussions",
	CHANGELOG: "https://github.com/Zentar-Ai/Roo-Code/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/Zentar-Ai/Roo-Code/blob/main/PRIVACY.md",
	INTEGRATIONS: "https://docs.zentar.ai/community",
	TUTORIALS: "https://docs.zentar.ai/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=ZentarAI.roo-code",
	SECURITY: "https://trust.roocode.com",
	EVALS: "https://roocode.com/evals",
	BLOG: "https://blog.roocode.com",
	OFFICE_HOURS_PODCAST: "https://www.youtube.com/@RooCodeYT/podcasts",
	FAQ: "https://roocode.com/#faq",
	TESTIMONIALS: "https://roocode.com/#testimonials",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
}
